config/routes.rb
Rails.application.routes.draw do
  root to: 'issues#index'
  devise_for :users
  resources :users
  resources :issues
  resources :comments, only: %i(create edit update destroy)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :issue
end

app/models/issue.rb
class Issue < ApplicationRecord
  STATES = { new: 0, in_progress: 1, suspended: 2, on_review: 3, done: 4, closed: 5 }.freeze

  has_many :comments, -> { order(created_at: :asc) }
  has_and_belongs_to_many :participants,
                          join_table: 'issues_users',
                          class_name: User,
                          association_foreign_key: :user_id,
                          primary_key: :issue_id

  validates_presence_of :title

  accepts_nested_attributes_for :participants,
                                allow_destroy: true,
                                reject_if: -> (record) { record[:id].nil? }

  def state
    read_attribute(:state).humanize
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_and_belongs_to_many :issues

  validates_presence_of :role

  enum role: { user: 0, admin: 2 }

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/authorization_controller.rb
class AuthorizationController < ApplicationController
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < AuthorizationController
  before_action :find_comment, only: %i(edit update destroy)

  def create
    authorize :comment
    @comment = Comment.new(permitted_attributes(Comment))
    if @comment.save
      redirect_back(fallback_location: root_path, notice: 'Comment created.')
    else
      flash[:alert] = @comment.errors.full_messages.join('<br>').html_safe
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    if @comment.update(permitted_attributes(@comment))
      redirect_to @comment.issue, notice: 'Comment updated.'
    else
      flash[:alert] = @comment.errors.full_messages.join('<br>').html_safe
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @comment.destroy
    redirect_back(fallback_location: root_path, notice: 'Comment deleted.')
  end

  private

  def find_comment
    @comment = Comment.find(params[:id])
    authorize @comment
  end
end

app/controllers/issues_controller.rb
class IssuesController < AuthorizationController
  before_action :find_issue, only: %i(update show edit destroy)

  def index
    authorize Issue
    @issues = policy_scope(Issue).order('id desc').page(params[:page])
  end

  def new
    @issue = Issue.new
    @issue.participant_ids << current_user.id unless current_user.admin?
    authorize(@issue)
  end

  def create
    authorize :issue
    @issue = Issue.new(permitted_attributes(Issue))
    if @issue.save
      redirect_to @issue, notice: 'Issue created.'
    else
      flash[:alert] = @issue.errors.full_messages.join('<br>').html_safe
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    if @issue.update(permitted_attributes(@issue))
      redirect_to @issue, notice: 'Issue updated.'
    else
      flash[:alert] = @issue.errors.full_messages.join('<br>').html_safe
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @issue.destroy
    redirect_to issues_path, notice: 'Issue deleted.'
  end

  private

  def find_issue
    @issue = Issue.find(params[:id])
    authorize @issue
  end
end

app/controllers/users_controller.rb
class UsersController < AuthorizationController
  before_action :find_user, only: %i(update destroy show edit)

  def index
    authorize User
    @users = policy_scope(User)
  end

  def update
    if @user.update_attributes(permitted_attributes(@user))
      redirect_to users_path, notice: 'User updated.'
    else
      flash[:alert] = @user.errors.full_messages.join('<br>').html_safe
      redirect_to users_path
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

  private

  def find_user
    @user = User.find(params[:id])
    authorize @user
  end

  def sanitize_params
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params.delete[:password]
      params.delete[:password_confirmation]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_display.html.haml
.container
  .row
    .col-md-9
      %ul.list-inline
        %li
          %b= comment.user.name
        %li
          .small= comment.created_at.strftime('%T %d.%m.%y')
        - if comment.created_at < comment.updated_at
          %li
            .small= "(Updated: #{comment.updated_at.strftime('%T %d.%m.%y')})"
        - if policy(comment).destroy?
          %li
            .small
              = link_to 'delete', comment_url(comment), method: :delete
        - if policy(comment).edit?
          %li
            .small
              = link_to 'edit', edit_comment_url(comment)

      %p= comment.content

app/views/comments/_form.html.haml
= form_for(comment) do |f|
  = f.hidden_field :issue_id
  = f.hidden_field :user_id, value: current_user.id
  .form-group
    = f.label :content, 'Message'
    = f.text_area :content, rows: 5, class: 'form-control'
  = f.submit 'Send', class: 'btn btn-primary'

app/views/comments/edit.html.haml
.container
  .row
    .col-md-6
      %h3 Edit comment
      = render 'form', comment: @comment

app/views/issues/_extra_info.html.haml
.row
  .col-sm-12
    %ul.list-inline
      %li
        %b State:
      %li= @issue.state

  .col-sm-12
    %b Participants:
    %ul.list-unstyled
      - @issue.participants.each do |user|
        %li= link_to user.name, user_path(user)

  .col-sm-12
    - if @issue.label.present?
      %ul.list-inline
        %li
          %b Label:
        %li= @issue.label

app/views/issues/_form.html.haml
= form_for(issue) do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control'
  .form-group
    = f.label :state
    = f.select :state, Issue::STATES.keys.map { |state| [state.to_s.humanize, state] }, {}, class: 'form-control'
  .form-group
    = f.select :participant_ids, User.all.map { |user| [user.name, user.id] }, {}, class: 'form-control', role: 'select2', include_blank: true, multiple: true
  = f.submit 'Save changes', class: 'btn btn-primary'

app/views/issues/edit.html.haml
.container
  .row
    .col-md-6
      %h3 Edit issue
      = render 'form', issue: @issue

app/views/issues/index.html.haml
.container
  .row
    .col-lg-12
      %h1.page-header Issues
      %div
        = link_to 'Add Issue', new_issue_path, class: 'btn btn-primary'
      = paginate @issues, theme: 'twitter-bootstrap-3'
      .table-responsive
        %table.table
          %thead
            %tr
              %th ID
              %th Title
              %th State
          %tbody
            - @issues.each do |issue|
              %tr
                %th{scope: 'row'}= issue.id
                %td= link_to issue.title, issue_path(issue)
                %td= issue.state
      = paginate @issues, theme: 'twitter-bootstrap-3'

app/views/issues/new.html.haml
.container
  .row
    .col-md-6
      %h3 New issue
      = render 'form', issue: @issue

app/views/issues/show.html.haml
.container
  %h2
    = @issue.title
    - if policy(@issue).edit?
      .pull-right= link_to 'Edit Isuue', edit_issue_path(@issue), class: 'btn btn-primary btn-sm'

  .row
    .col-md-9
      %p= @issue.description

      %h3 Comments:
      - if @issue.comments.size > 0
        - @issue.comments.each do |comment|
          =render 'comments/display', comment: comment
      - else
        %p No comments yet

      - if policy(@issue).update?
        %h4 Write a comment
        = render 'comments/form', comment: @issue.comments.build

    .col-md-3
      .panel.panel-default
        .panel-body
          = render 'extra_info'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg.html_safe, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  - if current_user.try(:admin?)
    %li= link_to 'Users', users_path

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if current_user
  - if policy(:issue).index?
    %li= link_to 'Issues', issues_path
  - if policy(:user).index?
    %li= link_to 'Users', users_path
  %li= link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Task Tracker'
    %meta{name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Task Tracker'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{ role: 'main' }
      = render 'layouts/messages'
      = yield

app/views/users/_user.html.haml
%td
  = link_to user.email, user
%td
  = user.role.capitalize
%td
  - if policy(user).edit?
    = link_to('Edit user', edit_user_path(user), class: 'button-xs')
%td
  - if policy(user).destroy?
    = link_to('Delete user', user_path(user), data: { confirm: 'Are you sure?' }, method: :delete, class: 'button-xs')

app/views/users/edit.html.haml
.container
  .row
    .col-md-6
      %h3 Edit user

      = form_for(@user) do |f|
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :email
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.label :password
          = f.text_field :password, class: 'form-control', type: 'password'
        .form-group
          = f.label :password_confirmation
          = f.text_field :password_confirmation, class: 'form-control', type: 'password'
        .form-group
          = f.label :role
          = f.select :role, User.roles.keys.map { |role| [role.titleize, role] }, {}, class: 'form-control'
        = f.submit 'Update', class: 'btn btn-primary'

app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %tbody
          - @users.each do |user|
            %tr
              = render user

app/views/users/show.html.haml
%h3 User
%p
  Name: #{@user.name if @user.name}
%p
  Email: #{@user.email if @user.email}